

; WaterTransparency
;   TransparentWaterMinOpacity = 1.0   ; opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
;   TransparentWaterDepth = 3.0       ; depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
; End


; -----------------
; AI Stuff
; -----------------

AIData
  AICrushesInfantry                   = NO    ; If yes, ai will attempt to crush infantry with vehicles.
End


; -----------------------
; Build Limits
; -----------------------

Object GLATankMarauder
  Buildable = NO
End

Object GLAInfantryJarmenKell
  Buildable = NO
End

Object GLAVehicleScudLauncher
  Buildable = NO
End

Object GLAInfantryHijacker
  Buildable = NO
End

Object GLAStingerSite
  Buildable = NO
End

Object GLAPalace
  Buildable = NO
End

Object GLAVehicleRocketBuggy
  Buildable = NO
End

Object GLAVehicleQuadCannon
  Buildable = NO
End

Object GLAInfantryAngryMobNexus
  Buildable = NO
End

Object GLAInfantryTerrorist
  Buildable = NO
End

Object GLAVehicleToxinTruck
  Buildable = NO
End

Object GLAVehicleBombTruck
  Buildable = NO
End

; Object GLAVehicleRadarVan
;   Buildable = NO
; End

Object GLACommandCenter
  Buildable = NO
End

Object GLAScudStorm
  Buildable = NO
End

Object GLABlackMarket
  Buildable = NO
End

Object ChinaVehicleNukeLauncher
  Buildable = NO
End

; Prisons are cut. sorry. (srj)
; Object GLAPrison
;   Buildable = NO
; End

Object GLADemoTrap
  Buildable = NO
End

Object ChinaGattlingCannon
  Buildable = NO
End

Object ChinaAirfield
  Buildable = NO
End

Object ChinaPropagandaCenter
  Buildable = NO
End

Object ChinaSpeakerTower
  Buildable = NO
End

Object ChinaNuclearMissileLauncher
  Buildable = NO
End

Object ChinaVehicleInfernoCannon
  Buildable = NO
End

Object ChinaTankDragon
  Buildable = NO
End

Object ChinaInfantryHacker
  Buildable = NO
End

Object ChinaVehicleTroopCrawler
  Buildable = NO
End

Object ChinaTankOverlord
  Buildable = NO
End

Object ChinaTankGattling
  Buildable = NO
End

Object ChinaInfantryBlackLotus
  Buildable = NO
End

Object ChinaNuclearMissileLauncher
  Buildable = NO
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ; opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ; depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

CommandSet SCIENCE_GLA_CommandSetRank1
  1 = Command_PurchaseScienceTechnicalTraining
  2 = Command_PurchaseScienceMarauderTank
  3 = Command_PurchaseScienceEmergencyRepair1
End

; Rank 3 assign buttons to position like so:
; 1 4 7 10
; 2 5 8 11
; 3 6 9 12
CommandSet SCIENCE_GLA_CommandSetRank3
  1 = Command_PurchaseScienceScudLauncher
  4 = Command_PurchaseScienceCashBounty1
  5 = Command_PurchaseScienceCashBounty2
  6 = Command_PurchaseScienceCashBounty3
  7 = Command_PurchaseScienceRebelAmbush1
  8 = Command_PurchaseScienceRebelAmbush2
  9 = Command_PurchaseScienceRebelAmbush3
  10 = Command_PurchaseScienceHijacker
End

; -------------------------------------
; GLA Sciences
; -------------------------------------

; --- LEVEL 1 POWERS ---
Science SCIENCE_ScudLauncher
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLASCUDLauncher
  Description = CONTROLBAR:ToolTipGLAScienceSCUDLauncher
End

Science SCIENCE_MarauderTank
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank1
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLAMaruaderTank
  Description = CONTROLBAR:ToolTipGLaScienceMarauderTank
End

Science SCIENCE_TechnicalTraining
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank1
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLATechnicalTraining
  Description = CONTROLBAR:ToolTipGLAScienceTechnicalTraining
End

; --- LEVEL 3 POWERS ---
Science SCIENCE_Hijacker
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLAHijacker
  Description = CONTROLBAR:ToolTipGLAScienceHijacker
End

Science SCIENCE_RebelAmbush1
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLARebelAmbush1
  Description = CONTROLBAR:ToolTipGLAScienceRebelAmbush
End

Science SCIENCE_RebelAmbush2
  PrerequisiteSciences = SCIENCE_RebelAmbush1 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLARebelAmbush2
  Description = CONTROLBAR:ToolTipGLAScienceRebelAmbush
End

Science SCIENCE_RebelAmbush3
  PrerequisiteSciences = SCIENCE_RebelAmbush2 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLARebelAmbush3
  Description = CONTROLBAR:ToolTipGLAScienceRebelAmbush
End

Science SCIENCE_CashBounty1
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLACashBounty1
  Description = CONTROLBAR:ToolTipGLAScienceCashBounty
End

Science SCIENCE_CashBounty2
  PrerequisiteSciences = SCIENCE_CashBounty1 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLACashBounty2
  Description = CONTROLBAR:ToolTipGLAScienceCashBounty
End

Science SCIENCE_CashBounty3
  PrerequisiteSciences = SCIENCE_CashBounty2 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLACashBounty3
  Description = CONTROLBAR:ToolTipGLAScienceCashBounty
End

; --- LEVEL 8 POWERS ---
Science SCIENCE_AnthraxBomb
  PrerequisiteSciences = SCIENCE_GLA SCIENCE_Rank5
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:GLAAnthraxBomb
  Description = CONTROLBAR:ToolTipGLAScienceAnthraxBomb
End


; --- LEVEL 3, Common to all sides ---
Science SCIENCE_EmergencyRepair1
  PrerequisiteSciences = SCIENCE_Rank1 ; No country Science requirement
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:EmergencyRepair1
  Description = CONTROLBAR:ToolTipScienceEmergencyRepair
End

Science SCIENCE_EmergencyRepair2
  PrerequisiteSciences = SCIENCE_CHINA SCIENCE_EmergencyRepair1 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:EmergencyRepair2
  Description = CONTROLBAR:ToolTipScienceEmergencyRepair
End

Science SCIENCE_EmergencyRepair3
  PrerequisiteSciences = SCIENCE_CHINA SCIENCE_EmergencyRepair2 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = YES
  DisplayName = SCIENCE:EmergencyRepair3
  Description = CONTROLBAR:ToolTipScienceEmergencyRepair
End



