; //////////////////////////////////////////////////////////////////////////////////////////////////
; FILE: Training01/Map.ini
; //////////////////////////////////////////////////////////////////////////////////////////////////

; Weapon USA01StingerMissileWeapon
;   PrimaryDamage = 10.0
;   PrimaryDamageRadius = 5.0
;   SecondaryDamage = 0.0
;   SecondaryDamageRadius = 0.0
;   AttackRange = 0.0
;   DamageType = EXPLOSION          ; ignored for projectile weapons
;   DeathType = EXPLODED
;   WeaponSpeed = 600               ; ignored for projectile weapons
;   ProjectileObject = StingerMissile
;   ProjectileExhaust = MissileExhaust
;   RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
;   DelayBetweenShots = 500  ; time between shots, msec
;   ClipSize = 1             ; how many shots in a Clip (0 == infinite)
;   ClipReloadTime = 1000    ; how long to reload a Clip, msec
;   AutoReloadsClip = YES
;   FireFX = FX_StingerMissileIgnition
;   FireSound = StingerMissileWeapon
;   ProjectileDetonationFX = WeaponFX_StingerMissileDetonation
;   AntiAirborneVehicle = NO
;   AntiAirborneInfantry = NO
;   AntiGround = YES
; End

; Object GLAInfantryStingerSoldier
;   WeaponSet
;     Conditions    = NONE
;     Weapon        = PRIMARY USA01StingerMissileWeapon
;   End
; End


; Rank 1
;   RankName                      = INI:RankLevel1
;   SkillPointsNeeded             = 0
;   SciencesGranted               = SCIENCE_Rank1
;   SciencePurchasePointsGranted  = 0
; End


Object GLAStingerSite
  RemoveModule ModuleTag_08  ; do not create a GLA hole
End

Object AmericaVehicleComanche
  IsTrainable         = NO
End

; -----------------
; AI Stuff
; -----------------

AIData

  AICrushesInfantry                   = NO ; If yes, ai will attempt to crush infantry with vehicles.
End




; -----------------------
; Build Limits
; -----------------------

Object GLAVehicleRadarVan
  Buildable = NO
End

Object AmericaSupplyCenter
  Buildable = NO
End

Object AmericaInfantryMissileDefender
  Buildable = NO
End

Object AmericaInfantryPathfinder
  Buildable = NO
End

Object AmericaBarracks
  Buildable = NO
End

Object AmericaPowerPlant
  Buildable = NO
End

Object AmericaWall
  Buildable = NO
End

Object AmericaAirfield
  Buildable = NO
End

Object AmericaPatriotBattery
  Buildable = NO
End

Object AmericaParticleCannonUplink
  Buildable = NO
End

Object AmericaSupplyDropZone
  Buildable = NO
End


Object AmericaStrategyCenter
  Buildable = NO
End

Object AmericaDetentionCamp
  Buildable = NO
End

Object AmericaCommandCenter
  Buildable = NO
End

Object AmericaVehicleTomahawk
  Buildable = NO
End

Object AmericaVehicleChinook
  Buildable = NO
  KindOf          = PRELOAD CAN_CAST_REFLECTIONS CAN_ATTACK VEHICLE TRANSPORT AIRCRAFT HARVESTER SCORE
End

Object AmericaVehicleMedic
  Buildable = NO
End

; Object AmericaTankPaladin
;   Buildable = NO
; End

; Object AmericaVehicleDozer
;   Buildable = NO
; End

Object AmericaInfantryRangerMissileTeam
  Buildable = NO
End

Object AmericaInfantryColonelBurton
  Buildable = NO
End

Object GLAPalace
  Buildable = NO
End

Object GLABlackMarket
  Buildable = NO
End

Object GLAScudStorm
  Buildable = NO
End

; Prisons are cut. sorry. (srj)
; Object GLAPrison
;   Buildable = NO
; End

Object GLADemoTrap
  Buildable = NO
End

Object GLAVehicleRocketBuggy
  Buildable = NO
End

Object GLAVehicleToxinTruck
  Buildable = NO
End

Object GLAInfantryAngryMobNexus
  Buildable = NO
End

Object GLAVehicleQuadCannon
  Buildable = NO
End

Object GLAVehicleBombTruck
  Buildable = NO
End

Object GLAInfantryTerrorist
  Buildable = NO
End

Object GLAInfantryJarmenKell
  Buildable = NO
End

Object GLAVehicleScudLauncher
  Buildable = NO
End

Object GLATankMarauder
  Buildable = NO
End

Object GLAInfantryHijacker
  Buildable = NO
End

